[meta]
name = "The Autism Spectrum Quotient"
slug = "perception-asq"
pattern = "multiple-choice"
version = "1.1.0"
category = "Perception"
analyzer = true
image = "http://res.cloudinary.com/myway-learning-company/image/upload/w_120,h_120/v1402453482/tgirmbkzl75piy8lo0ff.jpg"
algorithm = "asq"
resultDisplayType = "pie"

resultExplanation = """
Psychologist Simon Baron-Cohen and his colleagues at Cambridge's Autism Research \
Centre have created the Autism-Spectrum Quotient, or AQ, as a measure of the \
extent of autistic traits in adults. In the first major trial using the test, \
the average score in the control group was 16.4. Eighty percent of those \
diagnosed with autism or a related disorder scored 32 or higher. The test is not \
a means for making a diagnosis, however, and many who score above 32 and even \
meet the diagnostic criteria for mild autism or Asperger's report no difficulty \
functioning in their everyday lives.
"""

description = """
This exploration is a fun indicator of how you may function. \
It is not a means for making a diagnosis. \
It's only to make you think about how you prefer to engage with others. \
You may walk among many who score above 32 and even meet the diagnostic criteria for mild autism or Asperger's. \
That does not mean you are on the spectrum. \
The autism-spectrum quotient (AQ), was a questionnaire published \
in 2001 by Simon Baron-Cohen and his colleagues at the Autism Research Centre in Cambridge, UK. \
The test was popularised by Wired in December 2001.
"""

# IF YOU CHANGE THE ORDER OF THE QUESTIONS OR ANSWERS, YOU MUST RELEASE A NEW MAJOR VERSION
# OF THIS EXPLORATION
[answers]
1 = "Definitely Agree"
2 = "Slightly Agree"
3 = "Slightly Disagree"
4 = "Definitely Disagree"

[questions]
1  = "I prefer to do things with others rather than on my own."
2  = "I prefer to do things the same way over and over again."
3  = "If I try to imagine something, I find it very easy to create a picture in my mind."
4  = "I frequently get so strongly absorbed in one thing that I lose sight of other things."
5  = "I often notice small sounds when others do not."
6  = "I usually notice car number plates or similar strings of information."
7  = "Other people frequently tell me that what I've said is impolite, even though I think it is polite."
8  = "When I'm reading a story, I can easily imagine what the characters might look like."
9  = "I am fascinated by dates."
10 = "In a social group, I can easily keep track of several different people's conversations."
11 = "I find social situations easy."
12 = "I tend to notice details that others do not."
13 = "I would rather go to a library than to a party."
14 = "I find making up stories easy."
15 = "I find myself drawn more strongly to people than to things."
16 = "I tend to have very strong interests, which I get upset about if I can't pursue."
17 = "I enjoy social chitchat."
18 = "When I talk, it isn't always easy for others to get a word in edgewise."
19 = "I am fascinated by numbers."
20 = "When I'm reading a story, I find it difficult to work out the characters' intentions."
21 = "I don't particularly enjoy reading fiction."
22 = "I find it hard to make new friends."
23 = "I notice patterns in things all the time."
24 = "I would rather go to the theater than to a museum."
25 = "It does not upset me if my daily routine is disturbed."
26 = "I frequently find that I don't know how to keep a conversation going."
27 = "I find it easy to 'read between the lines' when someone is talking to me."
28 = "I usually concentrate more on the whole picture, rather than on the small details."
29 = "I am not very good at remembering phone numbers."
30 = "I don't usually notice small changes in a situation or a person's appearance."
31 = "I know how to tell if someone listening to me is getting bored."
32 = "I find it easy to do more than one thing at once."
33 = "When I talk on the phone, I'm not sure when it's my turn to speak."
34 = "I enjoy doing things spontaneously."
35 = "I am often the last to understand the point of a joke."
36 = "I find it easy to work out what someone is thinking or feeling just by looking at their face."
37 = "If there is an interruption, I can switch back to what I was doing very quickly."
38 = "I am good at social chitchat."
39 = "People often tell me that I keep going on and on about the same thing."
40 = "When I was young, I used to enjoy playing games involving pretending with other children."
41 = "I like to collect information about categories of things (e.g., types of cars, birds, trains, plants)."
42 = "I find it difficult to imagine what it would be like to be someone else."
43 = "I like to carefully plan any activities I participate in."
44 = "I enjoy social occasions."
45 = "I find it difficult to work out people's intentions."
46 = "New situations make me anxious."
47 = "I enjoy meeting new people."
48 = "I am a good diplomat."
49 = "I am not very good at remembering people's date of birth."
50 = "I find it very easy to play games with children that involve pretending."
