[meta]
name = "Values"
category = "Values and Principles"
version = "1.0.0"
slug = "values-basic"
image = "http://res.cloudinary.com/myway-learning-company/image/upload/w_120,h_120/v1402452536/ftcgqwipan5xosbduntm.jpg"
pattern = "heatmap"
analyzer = false

description = """
Life is full of choices. What do you value most?
"""

[answers]
1 = "I don't know or neutral"
2 = "must have (a core value)"
3 = "should have"
4 = "nice to have"
5 = "avoid"

[questions]
 1  =  'Accomplishment'
 2  =  'Accuracy'
 3  =  'Achievement'
 4  =  'Acknowledgment'
 5  =  'Action'
 6  =  'Adventure'
 7  =  'Aesthetics'
 8  =  'Affluence'
 9  =  'Ambition'
10  =  'Authenticity'
11  =  'Authority'
12  =  'Balance'
13  =  'Beauty'
14  =  'Bravery'
15  =  'Choice'
16  =  'Change'
17  =  'Collaboration'
18  =  'Competence'
19  =  'Community'
20  =  'Compassion'
21  =  'Connectedness'
22  =  'Consistency'
23  =  'Contribution'
24  =  'Courage'
25  =  'Creativity'
26  =  'Curiosity'
27  =  'Diligence'
28  =  'Diversity'
29  =  'Drive'
30  =  'Elegance'
31  =  'Empowerment'
32  =  'Empathy'
33  =  'Excellence'
34  =  'Fame'
35  =  'Fitness'
36  =  'Focus'
37  =  'Friends'
38  =  'Fun'
39  =  'Freedom'
40  =  'Grit'
41  =  'Growth'
42  =  'Harmony'
43  =  'Health'
44  =  'Honesty'
45  =  'Humor'
46  =  'Independence'
47  =  'Industriousness'
48  =  'Innovation'
49  =  'Integrity'
50  =  'Intelligence'
51  =  'Intensity'
52  =  'Intimacy'
53  =  'Joy'
54  =  'Justice'
55  =  'Kindness'
56  =  'Leadership'
57  =  'Learning'
58  =  'Leisure'
59  =  'Loyalty'
60  =  'Logic'
61  =  'Love'
62  =  'Money'
63  =  'Nature'
64  =  'Nurturing'
65  =  'Orderliness'
66  =  'Optimism'
67  =  'Openness'
68  =  'Participation'
69  =  'Passion'
70  =  'Peace'
71  =  'Philanthropy'
72  =  'Power'
73  =  'Play'
74  =  'Precision'
75  =  'Privacy'
76  =  'Productivity'
77  =  'Recognition'
78  =  'Respect'
79  =  'Risk'
80  =  'Tenacity'
81  =  'Trust'
82  =  'Romance'
83  =  'Self'
84  =  'Selflessness'
85  =  'Strength'
86  =  'Reliance'
87  =  'Service'
88  =  'Spirituality'
89  =  'Success'
90  =  'Tradition'
91  =  'Vitality'
92  =  'Wisdom'
93  =  'Hard Work'
