/* Replace with your SQL commands */
DROP TABLE IF EXISTS `OAuthAccessToken`;
DROP TABLE IF EXISTS `OAuth2ClientApplication`;
DROP TABLE IF EXISTS `ACL`;
DROP TABLE IF EXISTS `RoleMapping`;
DROP TABLE IF EXISTS `Role`;
DROP TABLE IF EXISTS `Comment`;
DROP TABLE IF EXISTS `Post`;
DROP TABLE IF EXISTS `DiscoveryResponse`;
DROP TABLE IF EXISTS `Discovery`;
DROP TABLE IF EXISTS `Supporter`;
DROP TABLE IF EXISTS `Invitation`;
DROP TABLE IF EXISTS `Share`;
DROP TABLE IF EXISTS `WaybookUserDetail`;
DROP TABLE IF EXISTS `WaybookUser`;

DROP TABLE IF EXISTS `OAuthAuthorizationCode`;
DROP TABLE IF EXISTS `OAuthPermission`;
DROP TABLE IF EXISTS `OAuthScopeMapping`;
DROP TABLE IF EXISTS `OAuthScope`;