#!/usr/bin/env node

'use strict';

require('dotenv').load();
var server = require('../server/server.js');

var ds = server.dataSources.db;

ds.discoverSchemas('WaybookUserDetail', {
    relations: true
}, function(err, schema) {
    if (err) {
        throw err;
    }
    console.log(JSON.stringify(schema, null, 2));
    ds.disconnect();
});
