#!/usr/bin/env node
'use strict';

var fs = require('fs');
var p = require('path');
var _ = require('lodash');
var jf = require('jsonfile');
var spec = require('swagger-tools').specs.v2;
var swaggerObject = require('./../common/api/swagger.json');
var codeGen = require('swagger-js-codegen').CodeGen;
var util = require('util');

// move into the common/api dir
process.chdir('common/api');

//console.log(swaggerObject);

spec.resolve(swaggerObject, function(err, result) {
  if (err) {
    console.log(err);
    throw err;

  }
  //console.log(util.inspect(result, {showHidden: false, depth: null}));
  //console.log(JSON.stringify(result, null, 2));

  var nodeSrc = codeGen.getNodeCode({className: 'Test', swagger: swaggerObject});
  console.log(nodeSrc);

});
