#!/usr/bin/env node

'use strict';

var spec = require('swagger-tools').specs.v2;
var swaggerObject = require('./../common/api/swagger.json');
var codeGen = require('swagger-js-codegen').CodeGen;

/**
 * move into the common/api dir
 */
process.chdir('common/api');

spec.resolve(swaggerObject, function(err, result) {
    if (err) {
        console.log(err);
        throw err;
    }

    var nodeSrc = codeGen.getNodeCode({
        className: 'Test',
        swagger: swaggerObject
    });

    console.log(nodeSrc);
});
