operationId: updateTask
description: Update task
"x-loopback-model": Task
"x-loopback-method": put
summary: Alters an task
tags:
  - tasks
parameters:
  - name: id
    in: path
    required: true
    type: string
  - name: patch
    description: Patch document describing alterations.
    in: body
    required: true
    schema:
      $ref: "#/definitions/PatchDocument"
responses:
  204:
    description: Successful patch
    schema:
      $ref: "#/definitions/Task"
  400:
    description: Malformed patch document
  415:
    description: Unsupported patch document
